### ISSUE TITLE
What do i, do?

### ISSUE THREAD

**Issue by TheLemon27** [JamSnack/TRandomizer-Mod#1]
no idea how to install this mod

help pls

**Comment by TheLemon27** [comment]
ok, now its working but now i have this:

Silently Caught Exception: Index was outside the bounds of the array.   at Terraria.NPC.AI_003_Fighters()   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at Terraria.NPC.AI_003_Fighters()
   at Terraria.NPC.VanillaAI()
   at Terraria.ModLoader.NPCLoader.NPCAI(NPC npc)
   at Terraria.NPC.UpdateNPC(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

**Comment by JamSnack** [comment]
Hi,

I'm not sure what exactly causes this bug but I do know that the game is
much more stable when playing Multiplayer. Even if you want to play
Singleplayer, you can start a solo LAN server and play alone, which should
nullify these issues.
